these were recommendations
This was what the cargo build returned, and I grasped barely enough to
make this commit as a result:

```
   Compiling racers-ledger-lamprey v0.1.0 (/usr/src/myapp/racers-ledger-lamprey)
error[E0277]: the trait bound `url::Url: IntoClientRequest` is not satisfied
   --> racers-ledger-lamprey/src/main.rs:372:27
    |
372 |             connect_async(Url::parse(connect_destination.as_str()).unwrap())
    |             ------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `IntoClientRequest` is not implemented for `url::Url`
    |             |
    |             required by a bound introduced by this call
    |
    = help: the following other types implement trait `IntoClientRequest`:
              httparse::Request<'h, 'b>
              ClientRequestBuilder
              async_tungstenite::tungstenite::http::Request<()>
              async_tungstenite::tungstenite::http::Uri
              std::string::String
              &'a str
              &'a std::string::String
              &'a async_tungstenite::tungstenite::http::Uri
note: required by a bound in `connect_async`
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-tungstenite-0.27.0/src/tokio.rs:369:8
    |
365 | pub async fn connect_async<R>(
    |              ------------- required by a bound in this function
...
369 |     R: IntoClientRequest + Unpin,
    |        ^^^^^^^^^^^^^^^^^ required by this bound in `connect_async`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `racers-ledger-lamprey` (bin "racers-ledger-lamprey") due to previous error
``̀`

After striking the Url::parse call (and it's .unwrap()) the error seemed to vanish, but got replaced by this:

```
kandre@f5527a45d07c:~$ cargo build
   Compiling racers-ledger-lamprey v0.1.0 (/usr/src/myapp/racers-ledger-lamprey)
warning: unused import: `url::Url`
  --> racers-ledger-lamprey/src/main.rs:12:5
   |
12 | use url::Url;
   |     ^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error[E0004]: non-exhaustive patterns: `async_tungstenite::tungstenite::Message::Frame(_)` not covered
   --> racers-ledger-lamprey/src/main.rs:388:19
    |
388 |             match msg {
    |                   ^^^ pattern `async_tungstenite::tungstenite::Message::Frame(_)` not covered
    |
note: `async_tungstenite::tungstenite::Message` defined here
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tungstenite-0.23.0/src/protocol/message.rs:160:1
    |
160 | pub enum Message {
    | ^^^^^^^^^^^^^^^^
...
176 |     Frame(Frame),
    |     ----- not covered
    = note: the matched value is of type `async_tungstenite::tungstenite::Message`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
    |
434 ~                 },
435 +                 async_tungstenite::tungstenite::Message::Frame(_) => todo!()
    |

For more information about this error, try `rustc --explain E0004`.
warning: `racers-ledger-lamprey` (bin "racers-ledger-lamprey") generated 1 warning
error: could not compile `racers-ledger-lamprey` (bin "racers-ledger-lamprey") due to previous error; 1 warning emitted
kandre@f5527a45d07c:~$ rustc --explain E0004
``̀`

I have actually no idea if that works, just that it compiles... I simply did not find the spot in the docs that tells me what a Message::Frame actually is..